from werkzeug.datastructures.structures import MultiDict

global dl
global multi_dict

dl = [
    "10,000 Hours - Dan + Shay, Justin Bieber",
    "16 Shots - Stefflon Don",
    "1979 - Smashing Pumpkins",
    "2 Be Loved - Lizzo",
    "2 Billion - Chaos Bay",
    "24K Magic - Bruno Mars",
    "3 Nights - Dominic Fike",
    "7 Days - Craig David",
    "7 rings - Ariana Grande",
    "9 to 5 - Dolly Parton",
    "A Thousand Miles - Vanessa Carlton",
    "abc (nicer) - GAYLE",
    "Alejandro - Lady Gaga",
    "All About That Bass - Meghan Trainor",
    "All My Life - Foo Fighters",
    "All Night - The Vamps, Matoma",
    "All the Small Things - blink-182",
    "Alright - Supergrass",
    "Always On Time - Ja Rule",
    "American Idiot - Green Day",
    "American Pie - Don McLean",
    "Anaconda - Nicki Minaj",
    "Animals - Martin Garrix",
    "Anna Julia - Los Hermanos",
    "Anomalies - Aphyxion",
    "Any Man of Mine - Shania Twain",
    "Ao to Natsu - Mrs.GREEN APPLE",
    "Apollo - Porno Graffitti",
    "Back pocket - Vulfpeck",
    "Back To You - Selena Gomez",
    "Bad Guy - Billie Eilish",
    "Bad Habit - Steve Lacy",
    "Bad Habits - Ed Sheeran",
    "Bad Romance - Lady Gaga",
    "Baddie - MK xyz",
    "Bam Bam - Camila Cabello, Ed Sheeran",
    "Bang Bang - Jessie J, Ariana Grande, Nicki Minaj",
    "Bank Account - 21 Savage",
    "Basket Case - Green Day",
    "Be Careful With A Fool - Johnny Winter",
    "Before You Go - Lewis Capaldi",
    "Believer - Imagine Dragons",
    "Belly Dancer - Imanbek, BYOR",
    "Biscuit Town - King Krule",
    "Black And Gold - Sam Sparro",
    "Black and Yellow - Wiz Khalifa",
    "Black Hole - Griff",
    "Bleed Me Dry - Electric Enemy",
    "Bleeding Out - Imagine Dragons",
    "Blinding Lights - The Weeknd",
    "Blue Monday - New Order",
    "Bodysnatchers - Radiohead",
    "Bones - Imagine Dragons",
    "Bonfire - Knife Party",
    "Bonkers - Dizzee Rascal, Armand Van Helden",
    "Boom Boom Pow - The Black Eyed Peas",
    "Boom Clap - Charli XCX",
    "Boom, Boom, Boom, Boom! - Vengaboys",
    "Born To Be Wild - Steppenwolf",
    "Brawl Stars Theme - Supercell",
    "Break Free - Ariana Grande, Zedd",
    "Breaking The Law - Judas Priest",
    "Broken Boy - Cage the Elephant",
    "Brown Sugar - D'Angelo",
    "Buck Rogers - Feeder",
    "Bulletproof - La Roux",
    "Burn This House - J. Worra, Little Boots",
    "Bury It - CHVRCHES",
    "Busy Earnin - Jungle",
    "Cake By The Ocean - DNCE",
    "Call Me Maybe - Carly Rae Jepsen",
    "Call On Me (Remix) - Starley, Ryan Riback",
    "Can I Go Away - Amor Amor",
    "Can't Feel My Face - The Weeknd",
    "Can't Get You Out Of My Head - Kylie Minogue",
    "Can't Hold Us - Macklemore, Ryan Lewis",
    "Candy - Cameo",
    "Candy Cane Lane - Sia",
    "Candyman - Christina Aguilera",
    "Cars - Gary Numan",
    "Chandelier - Sia",
    "Cheap Thrills - Sia",
    "Chelsea Dagger - The Fratellis",
    "Cherub Rock - Smashing Pumpkins",
    "Chocolate - The 1975",
    "Chrome Valley Customs Theme - Powertrain, James Elsey",
    "Chun-Li - Nicki Minaj",
    "Cinderella Man - Eminem",
    "Circles - Post Malone",
    "Clash of Clans Theme - Supercell",
    "Clash Royale Theme - Supercell",
    "Clocks - Coldplay",
    "Cold Heart (PNAU Remix) - Elton John, Dua Lipa",
    "Come & Go - Juice WRLD, Marshmello",
    "Come Get It Bae - Pharrell Williams",
    "Comin' In Hotta - Halo Sol",
    "Congratulations - Post Malone, Quavo",
    "Cool for the Summer - Demi Lovato",
    "Country Boy Do - Nelly, Tyler Hubbard",
    "Country Girl (Shake It For Me) - Luke Bryan",
    "Crash - The Primitives",
    "Crazy - Gnarls Barkley",
    "Crush - Tessa Violet",
    "Crystalised - The XX",
    "Cupid’s Chokehold / Breakfast in America - Gym Class Heroes",
    "Dance Monkey - Tones and I",
    "Dance, Dance - Fall Out Boy",
    "Dancing On My Own - Robyn",
    "Dare - Gorillaz",
    "Dashstar* - Knock2",
    "Dear Maria, Count Me In - All Time Low",
    "death bed (coffee for your head) - Powfu, beabadoobee",
    "Debaser - Pixies",
    "Deep Blue - Beatstar Originals",
    "Deeper Deeper - ONE OK ROCK",
    "Dem Boy Paigon - J Hus",
    "Demons - Imagine Dragons",
    "DEPARTURES - globe",
    "Dilemma - Nelly, Kelly Rowland",
    "Disco 2000 - Pulp",
    "Domino - Jessie J",
    "Don't Call Me Up - Mabel",
    "Don't Cha - The Pussycat Dolls",
    "Don't Fear The Reaper - Blue Öyster Cult",
    "Don't Look Back Into The Sun - The Libertines",
    "Don't Speak - No Doubt",
    "Don't Stop The Party - Drunk Girl",
    "Don't You (Forget About Me) - Simple Minds",
    "DON'T YOU WORRY - The Black Eyed Peas, Shakira, David Guetta",
    "Down With The Sickness - Disturbed",
    "Dreamer - Livin’ Joy",
    "Drunk (And I Don't Wanna Go Home) - Elle King, Miranda Lambert",
    "Du hast - Rammstein",
    "Duality - Slipknot",
    "Easy Love - Sigala",
    "Electric Feel - MGMT",
    "Electric Worry - Clutch",
    "Enemy - Imagine Dragons, JID",
    "Enola Gay - Orchestral Manoeuvres In The Dark",
    "Enter Sandman - Metallica",
    "Every You Every Me - Placebo",
    "Everybody - Logic",
    "Everybody (Backstreet's Back) - Backstreet Boys",
    "Everybody Falls (Fall Guys Theme) - Jukio Kallio & Daniel Hagström",
    "Everyday - Logic, Marshmello",
    "Faded - ZHU",
    "Fairytale of New York - The Pogues, Kirsty MacColl",
    "Fall In Love - Bailey Zimmerman",
    "Fancy Like - Walker Hayes",
    "Feel Good Inc. - Gorillaz",
    "Feel It Still - Portugal. The Man",
    "Fell In love With a Girl - The White Stripes",
    "Figure It Out - Royal Blood",
    "Fireflies - Owl City",
    "Firestarter - The Prodigy",
    "Flamingo - Kero Kero Bonito",
    "Flash Pose - Pabllo Vittar, Charli XCX",
    "Flesh without Blood - Grimes",
    "Fogo - Garmiani, Julimar Santos",
    "Free - Mood II Swing Radio Edit - Ultra Nate",
    "Freestyler - Bomfunk MC's",
    "From The D 2 The LBC - Eminem, Snoop Dogg",
    "Funky Town - Lipps Inc.",
    "Gangnam Style - Psy",
    "Gecko (Overdrive) - Oliver Heldens, Becky Hill",
    "Genius - Labrinth, Sia, Diplo",
    "Get Ready 2013 - 2 Unlimited",
    "Get the Party Started - P!nk",
    "Getaway - Saint Motel",
    "Ghost In The Mirror - Mallory Knox",
    "Ghosts - Presets",
    "Gimme chocolate!! - BABYMETAL",
    "Gimme Some More - Busta Rhymes",
    "Give it away - Red Hot Chili Peppers",
    "Glue - Fickle Friends",
    "Go - The Chemical Brothers",
    "Go With The Flow - Queens of the Stone Age",
    "Go Your Own Way - Fleetwood Mac",
    "Godzilla - Eminem, Juice WRLD",
    "Gold Dust - DJ Fresh, CECILE",
    "golden hour - Jvke",
    "Golden Skans - Klaxons",
    "Good Time - Owl City, Carly Rae Jepsen",
    "Goodies - Ciara, Petey Pablo",
    "Habits (Stay High) - Tove Lo",
    "Hallowed Be Thy Name - Iron Maiden",
    "Happier - Marshmello, Bastille",
    "Happy Now - Kygo",
    "Hard Times - Paramore",
    "Hay Day Theme - Supercell",
    "He's The Greatest Dancer - Sister Sledge",
    "Headlights - Alok & Alan Walker, Kiddo",
    "Heads Explode - Monster Magnet",
    "Heads Will Roll - Yeah Yeah Yeahs",
    "Healing Lies - Brawl Stars, Bad Randoms",
    "Heart Of Glass - Blondie",
    "Heat Waves - Glass Animals",
    "Heavy Cross - Gossip",
    "Heavy Shadows - Aphyxion, IMMERSE",
    "Here It Goes Again - OK Go",
    "Hey Ya! - OutKast",
    "Hey, Soul Sister - Train",
    "High Hopes - Panic! At The Disco",
    "High Status - Lex Da Funk",
    "Higher Power - Coldplay",
    "Hit 'Em Up Style (Oops!) - Blu Cantrell",
    "Hold Me Closer - Elton John, Britney Spears",
    "Hold My Hand - Jess Glynne",
    "Home - Edward Sharpe & The Magnetic Zeros",
    "Honey, I'm Good - Andy Grammer",
    "Hotshot (Hot Lap League Theme) - Ultimate Studio, Tim Spicer, Yahor Milkota",
    "House of Jealous Lovers - The Rapture",
    "House Work - Jax Jones, Mike Dunn, MNEK",
    "How Do You Sleep? - Sam Smith",
    "How Long - Charlie Puth",
    "Hrs and Hrs - Muni Long",
    "HUMBLE. - Kendrick Lamar",
    "Hurricane - Luke Combs",
    "Hysteria - Muse",
    "I Ain't Worried - OneRepublic",
    "I AM WOMAN - Emmy Meli",
    "I Believe In A Thing Called Love - The Darkness",
    "I Got You - Jaylon Ashaun",
    "I Gotta Feeling - The Black Eyed Peas",
    "I Know A Little - Lynyrd Skynyrd",
    "I Like Him - Princess Nokia",
    "I Like Me Better - Lauv",
    "I Like To Move It - Reel 2 Real, The Mad Stuntman",
    "I Love U - The Chainsmokers",
    "I Think I'm OKAY - Machine Gun Kelly, YUNGBLUD, Travis Barker",
    "I Want It That Way - Backstreet Boys",
    "I Write Sins Not Tragedies - Panic! At The Disco",
    "I'm Gonna Be (500 Miles) - The Proclaimers",
    "I'm Yours - Jason Mraz",
    "In the Morning - Jaded",
    "Indigo - 88rising, NIKI",
    "Inferno - Mrs.GREEN APPLE",
    "Informer - Snow",
    "Insane In The Brain - Cypress Hill",
    "Intentions - Justin Bieber, Quavo",
    "Intergalactic - Beastie Boys",
    "Into You - Ariana Grande",
    "Is This Love - Bob Marley & The Wailers",
    "Is You Rollin' - Mobdiva",
    "Issues - Julia Michaels",
    "It's Tricky - Run-D.M.C.",
    "Jerusalema - Master KG, Nomcebo Zikode",
    "Jolene - Dolly Parton",
    "Judas - Lady Gaga",
    "Juicy - Doja Cat, Tyga",
    "Jungle Drum - Emilíana Torrini",
    "Just a Girl - No Doubt",
    "Just Dance - Lady Gaga",
    "Kill V. Maim - Grimes",
    "King - Years & Years",
    "Kryptonite - 3 Doors Down",
    "Lalala - Y2K, bbno$",
    "Last Night - Morgan Wallen",
    "Last Resort - Papa Roach",
    "Latch - Disclosure, Sam Smith",
    "Late Night Talking - Harry Styles",
    "Leave A Trace - CHVRCHES",
    "Leave Me Alone - Flipp Dinero",
    "Left and Right - Charlie Puth, Jung Kook of BTS",
    "Let Me Love You - Mario",
    "Level Up! - Beatstar Originals",
    "Levels - Avicii",
    "Light Switch - Charlie Puth",
    "Lithium - Nirvana",
    "Little Talks - Of Monsters and Men",
    "Livin' On A Prayer - Bon Jovi",
    "Lost - Linkin Park",
    "Love it if we made it - The 1975",
    "Love Like That - Mayer Hawthorne",
    "Love Me Like You Do - Ellie Goulding",
    "love nwantiti (ah ah ah) - CKay",
    "Love Sosa - Chief Keef",
    "Love The Way You Lie - Eminem, Rihanna",
    "Love You Like That - Dagny",
    "Love Yourself - Justin Bieber",
    "Love$ick - Mura Masa, A$AP Rocky",
    "Lovefool - The Cardigans",
    "Lullaby - Sigala, Paloma Faith",
    "Māchina Vibes - Nemesy",
    "Made You Look - Meghan Trainor",
    "Malibu - Miley Cyrus",
    "Man! I Feel Like A Woman - Shania Twain",
    "MANTRA - Bring Me The Horizon",
    "MEGITSUNE - BABYMETAL",
    "Milkshake - Kelis",
    "Mine - Bazzi",
    "Misery Business - Paramore",
    "Miss Independent - Ne-Yo",
    "Mistaken For Strangers - The National",
    "Mistletoe - Justin Bieber",
    "Money - Leikeli47",
    "Montero (Call Me By Your Name) - Lil Nas X",
    "Mood - 24kGoldn, iann dior",
    "More Than A Feeling - Boston",
    "Mortis Game - Brawl Stars, Bad Randoms",
    "Move on - Luxar, Delfy",
    "Move On Up - Curtis Mayfield",
    "Move Your Body - Öwnboss, Sevek",
    "Move Your Feet - Junior Senior",
    "Mr Brightside - The Killers",
    "Ms. Jackson - OutKast",
    "Murder She Wrote - Chaka Demus & Pliers",
    "My God Is The Sun - Queens of the Stone Age",
    "My Sharona - The Knack",
    "N95 - Kendrick Lamar",
    "Natural - Breland",
    "Neko - DISH//",
    "Never Gonna Give You Up - Rick Astley",
    "No Good - Kaleo",
    "No Hands - Waka Flocka Flame, Roscoe Dash, Wale",
    "No One Knows - Queens of the Stone Age",
    "No Scrubs - TLC",
    "No tears left to cry - Ariana Grande",
    "No Type - Rae Sremmurd",
    "Norf Norf - Vince Staples",
    "Not Fair - Lily Allen",
    "Not Ready For Love - TCTS, Maya B",
    "Numb - Linkin Park",
    "Ocean Drive - Duke Dumont",
    "Old Town Road - Remix - Lil Nas X, Billy Ray Cyrus",
    "On & On - Erykah Badu",
    "One of Us is the Killer - Dillinger Escape Plan",
    "One Thing Right - Marshmello, Kane Brown",
    "One Way Or Another - Blondie",
    "Ooh La La - Goldfrapp",
    "Outta Your Mind - Lil Jon, LMFAO",
    "Over and Over - Hot Chip",
    "Overdrive - Metrik, Grafix",
    "Painless - Wanne",
    "Panda - Desiigner",
    "Panini - Lil Nas X",
    "Party Hard - Andrew W.K.",
    "Party In The U.S.A. - Miley Cyrus",
    "Party Rock Anthem - LMFAO",
    "Perfect Strangers - Jonas Blue",
    "Persistence - Beatstar Originals",
    "Peru - Fireboy DML, Ed Sheeran",
    "Plasma - Sharks",
    "Plug in Baby - Muse",
    "Poker Face - Lady Gaga",
    "Pompeii - Bastille",
    "Pony - Ginuwine",
    "Post Malone - Sam Feldt",
    "Post That - Leikeli47",
    "Praise You - Fatboy Slim",
    "PRBLMS - 6LACK",
    "Promises - NERO",
    "psychofreak - Camila Cabello, Willow",
    "Push It - Salt-N-Pepa",
    "Put Your Records On - Corinne Bailey Rae",
    "Rabbits Foot - Turbowolf",
    "Radiate - Enter Shikari",
    "Radio - Decora",
    "Radioactive - Imagine Dragons",
    "Ransom - Lil Tecca, Juice WRLD",
    "RAPSTAR - Polo G",
    "Red Flag - Billy Talent",
    "Red Room - Offset",
    "Rehab - Amy Winehouse",
    "Ride It - Regard",
    "Ridin - Chamillionaire, Krayzie Bone",
    "Right Here, Right Now - Fatboy Slim",
    "Riptide - The Chainsmokers",
    "Riptide - Vance Joy",
    "Rock Your Body - Justin Timberlake",
    "rockstar - Post Malone, 21 Savage",
    "Rockstar - Nickelback",
    "Rockstar - Timmy Trumpet, Sub Zero Project, DV8",
    "Roots Bloody Roots - Sepultura",
    "Rover - S1mba, DTG",
    "Run - Skan",
    "Rydeen - YELLOW MAGIC ORCHESTRA",
    "Sabotage - Beastie Boys",
    "Sandstorm - Darude",
    "Santeria - Sublime",
    "Satisfy - NERO",
    "Say So - Doja Cat",
    "Seasons - Thirty Seconds To Mars",
    "Senorita - Justin Timberlake",
    "Sexy And I Know It - LMFAO",
    "Shape of You - Ed Sheeran",
    "Shivers - Ed Sheeran",
    "Shooting Stars - Bag Raiders",
    "Show das Poderosas - Anitta",
    "Shut Up And Dance - WALK THE MOON",
    "Since U Been Gone - Kelly Clarkson",
    "Sing - Ed Sheeran",
    "Sing it back - Boris Dlugosh Mix - Moloko",
    "Sk8er Boi - Avril Lavigne",
    "Slip Away - Perfume Genius",
    "Somebody Else - The 1975",
    "Someone You Loved - Lewis Capaldi",
    "Something Just Like This - The Chainsmokers, Coldplay",
    "Stacy's Mom - Fountains Of Wayne",
    "Stand Up Tall - Dizzee Rascal",
    "Starlight - Muse",
    "Starving - Hailee Steinfeld, Grey, Zedd",
    "Stay - Zedd, Alessia Cara",
    "Strangers - Sigrid",
    "Strike a Pose - Young T & Bugsey, Aitch",
    "Sugar - Maroon 5",
    "Sugar, We're Goin Down - Fall Out Boy",
    "Sunroof - Nicky Youre, dazy",
    "Super Bass - Nicki Minaj",
    "Super Freaky Girl - Nicki Minaj",
    "Super Leap Day (Capital Highway) - Roberto Bazzoni / Nitrome",
    "Superman - Goldfinger",
    "Superstar - Lupe Fiasco, Matthew Santos",
    "Surgeon Simulator (Theme Tune) - Bossa Studios / Black Heron",
    "Swang - Rae Sremmurd",
    "Sway Back - Nase Foi",
    "Sweatbox - Luxxly",
    "Sweet but Psycho - Ava Max",
    "Sweet Home Alabama - Lynyrd Skynyrd",
    "Sweetness - Jimmy Eat World",
    "Symphony - Clean Bandit, Zara Larsson",
    "Symphony Of Destruction - Megadeth",
    "Take Me Out - Franz Ferdinand",
    "Talk - Khalid, Disclosure",
    "Tears Dry On Their Own - Amy Winehouse",
    "Teenage Dirtbag - Wheatus",
    "thank u, next - Ariana Grande",
    "That Don't Impress Me Much - Shania Twain",
    "That's Not My Name - The Ting Tings",
    "That's The Way (I Like It) - KC & The Sunshine Band",
    "THATS WHAT I WANT - Lil Nas X",
    "The Bad Touch - Bloodhound Gang",
    "The beginning - ONE OK ROCK",
    "The Business - Tiesto",
    "The Devil Went Down To Georgia - Korn, Yelawolf",
    "The Drill - Magnificence & 7 Skies",
    "The Fast Lane - Space Ape Edition - Harry Shotta",
    "The Git Up - Blanco Brown",
    "The Heinrich Maneuver - Interpol",
    "The Impression That I Get - The Mighty Mighty Bosstones",
    "The Kids Are Coming - Tones and I",
    "The Less I Know the Better - Tame Impala",
    "The Middle - Jimmy Eat World",
    "The Middle - Zedd, Maren Morris, Grey",
    "The Mother We Share - CHVRCHES",
    "The Motherload - Mastodon",
    "The Seed - AURORA",
    "The Smell Of Dirt Is In The Air - Jim Guthrie & J.J. Ipsen",
    "The Touch - Stan Bush",
    "The Trooper - Iron Maiden",
    "The Wire - HAIM",
    "Therapy - Electric Enemy",
    "Think About Things - Daði Freyr",
    "This Could Be Us - Rae Sremmurd",
    "This Is How We Do It - Montell Jordan",
    "This Is War - Thirty Seconds To Mars",
    "Thrash Metal Cassette - Dinosaur Pile-Up",
    "Thrift Shop - Macklemore, Ryan Lewis, Wanz",
    "Thunderclouds - Labrinth, Sia, Diplo",
    "Time Is Running Out - Muse",
    "Time of Our Lives - Pitbull, Ne-Yo",
    "Time To Waste - Alkaline Trio",
    "Together - Brawl Stars, Bad Randoms",
    "Tonight, Tonight - Smashing Pumpkins",
    "Tornado Of Souls - Megadeth",
    "Truth Hurts - Lizzo",
    "Tubthumping - Chumbawamba",
    "Turbo - The Nah",
    "Tusa - KAROL G, Nicki Minaj",
    "TWINNEM - Coi Leray",
    "Two Princes - Spin Doctors",
    "U Can't Touch This - MC Hammer",
    "Unholy - Sam Smith, Kim Petras",
    "USSEEWA - Ado",
    "Vegas - Doja Cat",
    "Viva La Vida - Coldplay",
    "Wait A Minute! - Willow",
    "Wake Me Up - Avicii",
    "Waking Up Dreaming - Shania Twain",
    "Walk Idiot Walk - The Hives",
    "Walking on a Dream - Empire of the Sun",
    "We Are Family - Sister Sledge",
    "We Different - KULLAH, Jessy Covets",
    "We Live Forever - The Prodigy",
    "We Won't Cooperate - Brawl Stars, Bad Randoms",
    "What A Man Gotta Do - Jonas Brothers",
    "What Do You Mean? - Justin Bieber",
    "What I Got - Sublime",
    "What Would You Do? - City High",
    "What You Gonna Do - MADZI",
    "What You Know - Two Door Cinema Club",
    "What's Golden - Jurassic 5",
    "Whenever, Wherever - Shakira",
    "Where's your head at - Basement Jaxx",
    "Whiskey Glasses - Morgan Wallen",
    "White Iverson - Post Malone",
    "White Noise - Disclosure, AlunaGeorge",
    "Who Let The Dogs Out? - Baha Men",
    "Wish - Alien Ant Farm",
    "WITHOUT YOU - The Kid LAROI",
    "Wolf like me - TV on the radio",
    "Wolves - Selena Gomez, Marshmello",
    "Word Up - Cameo",
    "Wynona's Big Brown Beaver - Primus",
    "XO Tour Llif3 - Lil Uzi Vert",
    "You Don't Know - 702",
    "You Really Got Me - The Kinks",
    "you should see me in a crown - Billie Eilish",
    "You Spin Me Round (Like a Record) - Murder Mix - Dead Or Alive",
    "Young Dumb & Broke - Khalid",
    "Youngblood - 5 Seconds of Summer",
    "Your Song - Rita Ora",
    "Yuh - Illvis Freshly"
]

dictIDtoName = {
    359: "10,000 Hours - Dan + Shay, Justin Bieber",
    322: "16 Shots - Stefflon Don",
    185: "1979 - Smashing Pumpkins",
    418: "2 Be Loved - Lizzo",
    438: "2 Billion - Chaos Bay",
    25: "24K Magic - Bruno Mars",
    165: "3 Nights - Dominic Fike",
    237: "7 Days - Craig David",
    263: "7 rings - Ariana Grande",
    425: "9 to 5 - Dolly Parton",
    218: "A Thousand Miles - Vanessa Carlton",
    221: "abc (nicer) - GAYLE",
    317: "Alejandro - Lady Gaga",
    504: "All About That Bass - Meghan Trainor",
    116: "All My Life - Foo Fighters",
    44: "All Night - The Vamps, Matoma",
    228: "All the Small Things - blink-182",
    87: "Alright - Supergrass",
    431: "Always On Time - Ja Rule",
    174: "American Idiot - Green Day",
    364: "American Pie - Don McLean",
    118: "Anaconda - Nicki Minaj",
    24: "Animals - Martin Garrix",
    206: "Anna Julia - Los Hermanos",
    423: "Anomalies - Aphyxion",
    512: "Any Man of Mine - Shania Twain",
    111: "Ao to Natsu - Mrs.GREEN APPLE",
    184: "Apollo - Porno Graffitti",
    42: "Back pocket - Vulfpeck",
    496: "Back To You - Selena Gomez",
    69: "Bad Guy - Billie Eilish",
    493: "Bad Habit - Steve Lacy",
    483: "Bad Habits - Ed Sheeran",
    11: "Bad Romance - Lady Gaga",
    318: "Baddie - MK xyz",
    123: "Bam Bam - Camila Cabello, Ed Sheeran",
    156: "Bang Bang - Jessie J, Ariana Grande, Nicki Minaj",
    399: "Bank Account - 21 Savage",
    284: "Basket Case - Green Day",
    487: "Be Careful With A Fool - Johnny Winter",
    15: "Before You Go - Lewis Capaldi",
    62: "Believer - Imagine Dragons",
    395: "Belly Dancer - Imanbek, BYOR",
    33: "Biscuit Town - King Krule",
    502: "Black And Gold - Sam Sparro",
    172: "Black and Yellow - Wiz Khalifa",
    470: "Black Hole - Griff",
    428: "Bleed Me Dry - Electric Enemy",
    327: "Bleeding Out - Imagine Dragons",
    41: "Blinding Lights - The Weeknd",
    450: "Blue Monday - New Order",
    79: "Bodysnatchers - Radiohead",
    328: "Bones - Imagine Dragons",
    363: "Bonfire - Knife Party",
    253: "Bonkers - Dizzee Rascal, Armand Van Helden",
    95: "Boom Boom Pow - The Black Eyed Peas",
    316: "Boom Clap - Charli XCX",
    377: "Boom, Boom, Boom, Boom! - Vengaboys",
    346: "Born To Be Wild - Steppenwolf",
    173: "Brawl Stars Theme - Supercell",
    12: "Break Free - Ariana Grande, Zedd",
    492: "Breaking The Law - Judas Priest",
    402: "Broken Boy - Cage the Elephant",
    290: "Brown Sugar - D'Angelo",
    225: "Buck Rogers - Feeder",
    270: "Bulletproof - La Roux",
    457: "Burn This House - J. Worra, Little Boots",
    177: "Bury It - CHVRCHES",
    433: "Busy Earnin - Jungle",
    144: "Cake By The Ocean - DNCE",
    375: "Call Me Maybe - Carly Rae Jepsen",
    376: "Call On Me (Remix) - Starley, Ryan Riback",
    445: "Can I Go Away - Amor Amor",
    155: "Can't Feel My Face - The Weeknd",
    458: "Can't Get You Out Of My Head - Kylie Minogue",
    176: "Can't Hold Us - Macklemore, Ryan Lewis",
    86: "Candy - Cameo",
    153: "Candy Cane Lane - Sia",
    166: "Candyman - Christina Aguilera",
    162: "Cars - Gary Numan",
    197: "Chandelier - Sia",
    7: "Cheap Thrills - Sia",
    313: "Chelsea Dagger - The Fratellis",
    158: "Cherub Rock - Smashing Pumpkins",
    293: "Chocolate - The 1975",
    463: "Chrome Valley Customs Theme - Powertrain, James Elsey",
    404: "Chun-Li - Nicki Minaj",
    306: "Cinderella Man - Eminem",
    63: "Circles - Post Malone",
    71: "Clash of Clans Theme - Supercell",
    179: "Clash Royale Theme - Supercell",
    210: "Clocks - Coldplay",
    311: "Cold Heart (PNAU Remix) - Elton John, Dua Lipa",
    64: "Come & Go - Juice WRLD, Marshmello",
    203: "Come Get It Bae - Pharrell Williams",
    422: "Comin' In Hotta - Halo Sol",
    117: "Congratulations - Post Malone, Quavo",
    169: "Cool for the Summer - Demi Lovato",
    370: "Country Boy Do - Nelly, Tyler Hubbard",
    357: "Country Girl (Shake It For Me) - Luke Bryan",
    294: "Crash - The Primitives",
    292: "Crazy - Gnarls Barkley",
    136: "Crush - Tessa Violet",
    140: "Crystalised - The XX",
    119: "Cupid’s Chokehold / Breakfast in America - Gym Class Heroes",
    469: "Dance Monkey - Tones and I",
    122: "Dance, Dance - Fall Out Boy",
    319: "Dancing On My Own - Robyn",
    314: "Dare - Gorillaz",
    448: "Dashstar* - Knock2",
    291: "Dear Maria, Count Me In - All Time Low",
    128: "death bed (coffee for your head) - Powfu, beabadoobee",
    112: "Debaser - Pixies",
    473: "Deep Blue - Beatstar Originals",
    161: "Deeper Deeper - ONE OK ROCK",
    310: "Dem Boy Paigon - J Hus",
    325: "Demons - Imagine Dragons",
    262: "DEPARTURES - globe",
    195: "Dilemma - Nelly, Kelly Rowland",
    386: "Disco 2000 - Pulp",
    276: "Domino - Jessie J",
    219: "Don't Call Me Up - Mabel",
    55: "Don't Cha - The Pussycat Dolls",
    342: "Don't Fear The Reaper - Blue Öyster Cult",
    160: "Don't Look Back Into The Sun - The Libertines",
    498: "Don't Speak - No Doubt",
    468: "Don't Stop The Party - Drunk Girl",
    53: "Don't You (Forget About Me) - Simple Minds",
    4: "DON'T YOU WORRY - The Black Eyed Peas, Shakira, David Guetta",
    23: "Down With The Sickness - Disturbed",
    397: "Dreamer - Livin’ Joy",
    366: "Drunk (And I Don't Wanna Go Home) - Elle King, Miranda Lambert",
    38: "Du hast - Rammstein",
    405: "Duality - Slipknot",
    413: "Easy Love - Sigala",
    229: "Electric Feel - MGMT",
    78: "Electric Worry - Clutch",
    326: "Enemy - Imagine Dragons, JID",
    459: "Enola Gay - Orchestral Manoeuvres In The Dark",
    419: "Enter Sandman - Metallica",
    97: "Every You Every Me - Placebo",
    454: "Everybody - Logic",
    138: "Everybody (Backstreet's Back) - Backstreet Boys",
    298: "Everybody Falls (Fall Guys Theme) - Jukio Kallio & Daniel Hagström",
    231: "Everyday - Logic, Marshmello",
    297: "Faded - ZHU",
    34: "Fairytale of New York - The Pogues, Kirsty MacColl",
    356: "Fall In Love - Bailey Zimmerman",
    361: "Fancy Like - Walker Hayes",
    2: "Feel Good Inc. - Gorillaz",
    31: "Feel It Still - Portugal. The Man",
    40: "Fell In love With a Girl - The White Stripes",
    121: "Figure It Out - Royal Blood",
    189: "Fireflies - Owl City",
    14: "Firestarter - The Prodigy",
    489: "Flamingo - Kero Kero Bonito",
    252: "Flash Pose - Pabllo Vittar, Charli XCX",
    269: "Flesh without Blood - Grimes",
    381: "Fogo - Garmiani, Julimar Santos",
    125: "Free - Mood II Swing Radio Edit - Ultra Nate",
    351: "Freestyler - Bomfunk MC's",
    305: "From The D 2 The LBC - Eminem, Snoop Dogg",
    412: "Funky Town - Lipps Inc.",
    18: "Gangnam Style - Psy",
    355: "Gecko (Overdrive) - Oliver Heldens, Becky Hill",
    511: "Genius - Labrinth, Sia, Diplo",
    330: "Get Ready 2013 - 2 Unlimited",
    20: "Get the Party Started - P!nk",
    352: "Getaway - Saint Motel",
    499: "Ghost In The Mirror - Mallory Knox",
    76: "Ghosts - Presets",
    29: "Gimme chocolate!! - BABYMETAL",
    481: "Gimme Some More - Busta Rhymes",
    379: "Give it away - Red Hot Chili Peppers",
    516: "Glue - Fickle Friends",
    32: "Go - The Chemical Brothers",
    151: "Go With The Flow - Queens of the Stone Age",
    462: "Go Your Own Way - Fleetwood Mac",
    329: "Godzilla - Eminem, Juice WRLD",
    256: "Gold Dust - DJ Fresh, CECILE",
    383: "golden hour - Jvke",
    505: "Golden Skans - Klaxons",
    183: "Good Time - Owl City, Carly Rae Jepsen",
    335: "Goodies - Ciara, Petey Pablo",
    191: "Habits (Stay High) - Tove Lo",
    472: "Hallowed Be Thy Name - Iron Maiden",
    54: "Happier - Marshmello, Bastille",
    72: "Happy Now - Kygo",
    387: "Hard Times - Paramore",
    199: "Hay Day Theme - Supercell",
    295: "He's The Greatest Dancer - Sister Sledge",
    190: "Headlights - Alok & Alan Walker, Kiddo",
    362: "Heads Explode - Monster Magnet",
    26: "Heads Will Roll - Yeah Yeah Yeahs",
    149: "Healing Lies - Brawl Stars, Bad Randoms",
    340: "Heart Of Glass - Blondie",
    259: "Heat Waves - Glass Animals",
    257: "Heavy Cross - Gossip",
    495: "Heavy Shadows - Aphyxion, IMMERSE",
    353: "Here It Goes Again - OK Go",
    215: "Hey Ya! - OutKast",
    214: "Hey, Soul Sister - Train",
    373: "High Hopes - Panic! At The Disco",
    494: "High Status - Lex Da Funk",
    442: "Higher Power - Coldplay",
    268: "Hit 'Em Up Style (Oops!) - Blu Cantrell",
    407: "Hold Me Closer - Elton John, Britney Spears",
    518: "Hold My Hand - Jess Glynne",
    188: "Home - Edward Sharpe & The Magnetic Zeros",
    371: "Honey, I'm Good - Andy Grammer",
    303: "Hotshot (Hot Lap League Theme) - Ultimate Studio, Tim Spicer, Yahor Milkota",
    170: "House of Jealous Lovers - The Rapture",
    89: "House Work - Jax Jones, Mike Dunn, MNEK",
    236: "How Do You Sleep? - Sam Smith",
    441: "How Long - Charlie Puth",
    343: "Hrs and Hrs - Muni Long",
    388: "HUMBLE. - Kendrick Lamar",
    360: "Hurricane - Luke Combs",
    279: "Hysteria - Muse",
    444: "I Ain't Worried - OneRepublic",
    242: "I AM WOMAN - Emmy Meli",
    389: "I Believe In A Thing Called Love - The Darkness",
    477: "I Got You - Jaylon Ashaun",
    145: "I Gotta Feeling - The Black Eyed Peas",
    426: "I Know A Little - Lynyrd Skynyrd",
    168: "I Like Him - Princess Nokia",
    226: "I Like Me Better - Lauv",
    336: "I Like To Move It - Reel 2 Real, The Mad Stuntman",
    164: "I Love U - The Chainsmokers",
    261: "I Think I'm OKAY - Machine Gun Kelly, YUNGBLUD, Travis Barker",
    222: "I Want It That Way - Backstreet Boys",
    517: "I Write Sins Not Tragedies - Panic! At The Disco",
    315: "I'm Gonna Be (500 Miles) - The Proclaimers",
    73: "I'm Yours - Jason Mraz",
    84: "In the Morning - Jaded",
    5: "Indigo - 88rising, NIKI",
    152: "Inferno - Mrs.GREEN APPLE",
    434: "Informer - Snow",
    106: "Insane In The Brain - Cypress Hill",
    105: "Intentions - Justin Bieber, Quavo",
    465: "Intergalactic - Beastie Boys",
    241: "Into You - Ariana Grande",
    204: "Is This Love - Bob Marley & The Wailers",
    513: "Is You Rollin' - Mobdiva",
    186: "Issues - Julia Michaels",
    147: "It's Tricky - Run-D.M.C.",
    65: "Jerusalema - Master KG, Nomcebo Zikode",
    358: "Jolene - Dolly Parton",
    70: "Judas - Lady Gaga",
    142: "Juicy - Doja Cat, Tyga",
    66: "Jungle Drum - Emilíana Torrini",
    337: "Just a Girl - No Doubt",
    50: "Just Dance - Lady Gaga",
    61: "Kill V. Maim - Grimes",
    255: "King - Years & Years",
    283: "Kryptonite - 3 Doors Down",
    251: "Lalala - Y2K, bbno$",
    443: "Last Night - Morgan Wallen",
    223: "Last Resort - Papa Roach",
    9: "Latch - Disclosure, Sam Smith",
    427: "Late Night Talking - Harry Styles",
    239: "Leave A Trace - CHVRCHES",
    484: "Leave Me Alone - Flipp Dinero",
    275: "Left and Right - Charlie Puth, Jung Kook of BTS",
    410: "Let Me Love You - Mario",
    391: "Level Up! - Beatstar Originals",
    100: "Levels - Avicii",
    350: "Light Switch - Charlie Puth",
    48: "Lithium - Nirvana",
    6: "Little Talks - Of Monsters and Men",
    148: "Livin' On A Prayer - Bon Jovi",
    453: "Lost - Linkin Park",
    207: "Love it if we made it - The 1975",
    126: "Love Like That - Mayer Hawthorne",
    96: "Love Me Like You Do - Ellie Goulding",
    113: "love nwantiti (ah ah ah) - CKay",
    109: "Love Sosa - Chief Keef",
    307: "Love The Way You Lie - Eminem, Rihanna",
    19: "Love You Like That - Dagny",
    500: "Love Yourself - Justin Bieber",
    240: "Love$ick - Mura Masa, A$AP Rocky",
    3: "Lovefool - The Cardigans",
    178: "Lullaby - Sigala, Paloma Faith",
    439: "Māchina Vibes - Nemesy",
    384: "Made You Look - Meghan Trainor",
    488: "Malibu - Miley Cyrus",
    365: "Man! I Feel Like A Woman - Shania Twain",
    248: "MANTRA - Bring Me The Horizon",
    101: "MEGITSUNE - BABYMETAL",
    57: "Milkshake - Kelis",
    196: "Mine - Bazzi",
    60: "Misery Business - Paramore",
    201: "Miss Independent - Ne-Yo",
    247: "Mistaken For Strangers - The National",
    143: "Mistletoe - Justin Bieber",
    287: "Money - Leikeli47",
    258: "Montero (Call Me By Your Name) - Lil Nas X",
    99: "Mood - 24kGoldn, iann dior",
    451: "More Than A Feeling - Boston",
    167: "Mortis Game - Brawl Stars, Bad Randoms",
    486: "Move on - Luxar, Delfy",
    16: "Move On Up - Curtis Mayfield",
    288: "Move Your Body - Öwnboss, Sevek",
    331: "Move Your Feet - Junior Senior",
    368: "Mr Brightside - The Killers",
    480: "Ms. Jackson - OutKast",
    289: "Murder She Wrote - Chaka Demus & Pliers",
    271: "My God Is The Sun - Queens of the Stone Age",
    415: "My Sharona - The Knack",
    447: "N95 - Kendrick Lamar",
    369: "Natural - Breland",
    124: "Neko - DISH//",
    321: "Never Gonna Give You Up - Rick Astley",
    519: "No Good - Kaleo",
    175: "No Hands - Waka Flocka Flame, Roscoe Dash, Wale",
    30: "No One Knows - Queens of the Stone Age",
    409: "No Scrubs - TLC",
    213: "No tears left to cry - Ariana Grande",
    227: "No Type - Rae Sremmurd",
    83: "Norf Norf - Vince Staples",
    348: "Not Fair - Lily Allen",
    102: "Not Ready For Love - TCTS, Maya B",
    452: "Numb - Linkin Park",
    1: "Ocean Drive - Duke Dumont",
    273: "Old Town Road - Remix - Lil Nas X, Billy Ray Cyrus",
    110: "On & On - Erykah Badu",
    171: "One of Us is the Killer - Dillinger Escape Plan",
    367: "One Thing Right - Marshmello, Kane Brown",
    88: "One Way Or Another - Blondie",
    45: "Ooh La La - Goldfrapp",
    8: "Outta Your Mind - Lil Jon, LMFAO",
    296: "Over and Over - Hot Chip",
    300: "Overdrive - Metrik, Grafix",
    466: "Painless - Wanne",
    46: "Panda - Desiigner",
    198: "Panini - Lil Nas X",
    35: "Party Hard - Andrew W.K.",
    482: "Party In The U.S.A. - Miley Cyrus",
    85: "Party Rock Anthem - LMFAO",
    192: "Perfect Strangers - Jonas Blue",
    424: "Persistence - Beatstar Originals",
    137: "Peru - Fireboy DML, Ed Sheeran",
    507: "Plasma - Sharks",
    455: "Plug in Baby - Muse",
    274: "Poker Face - Lady Gaga",
    216: "Pompeii - Bastille",
    347: "Pony - Ginuwine",
    139: "Post Malone - Sam Feldt",
    243: "Post That - Leikeli47",
    312: "Praise You - Fatboy Slim",
    114: "PRBLMS - 6LACK",
    202: "Promises - NERO",
    238: "psychofreak - Camila Cabello, Willow",
    266: "Push It - Salt-N-Pepa",
    320: "Put Your Records On - Corinne Bailey Rae",
    49: "Rabbits Foot - Turbowolf",
    339: "Radiate - Enter Shikari",
    446: "Radio - Decora",
    324: "Radioactive - Imagine Dragons",
    234: "Ransom - Lil Tecca, Juice WRLD",
    378: "RAPSTAR - Polo G",
    398: "Red Flag - Billy Talent",
    497: "Red Room - Offset",
    157: "Rehab - Amy Winehouse",
    47: "Ride It - Regard",
    193: "Ridin - Chamillionaire, Krayzie Bone",
    385: "Right Here, Right Now - Fatboy Slim",
    17: "Riptide - The Chainsmokers",
    491: "Riptide - Vance Joy",
    393: "Rock Your Body - Justin Timberlake",
    146: "rockstar - Post Malone, 21 Savage",
    436: "Rockstar - Nickelback",
    334: "Rockstar - Timmy Trumpet, Sub Zero Project, DV8",
    107: "Roots Bloody Roots - Sepultura",
    349: "Rover - S1mba, DTG",
    437: "Run - Skan",
    74: "Rydeen - YELLOW MAGIC ORCHESTRA",
    416: "Sabotage - Beastie Boys",
    249: "Sandstorm - Darude",
    244: "Santeria - Sublime",
    91: "Satisfy - NERO",
    98: "Say So - Doja Cat",
    510: "Seasons - Thirty Seconds To Mars",
    474: "Senorita - Justin Timberlake",
    27: "Sexy And I Know It - LMFAO",
    440: "Shape of You - Ed Sheeran",
    392: "Shivers - Ed Sheeran",
    211: "Shooting Stars - Bag Raiders",
    217: "Show das Poderosas - Anitta",
    43: "Shut Up And Dance - WALK THE MOON",
    246: "Since U Been Gone - Kelly Clarkson",
    56: "Sing - Ed Sheeran",
    150: "Sing it back - Boris Dlugosh Mix - Moloko",
    39: "Sk8er Boi - Avril Lavigne",
    77: "Slip Away - Perfume Genius",
    68: "Somebody Else - The 1975",
    182: "Someone You Loved - Lewis Capaldi",
    133: "Something Just Like This - The Chainsmokers, Coldplay",
    421: "Stacy's Mom - Fountains Of Wayne",
    28: "Stand Up Tall - Dizzee Rascal",
    406: "Starlight - Muse",
    205: "Starving - Hailee Steinfeld, Grey, Zedd",
    299: "Stay - Zedd, Alessia Cara",
    286: "Strangers - Sigrid",
    90: "Strike a Pose - Young T & Bugsey, Aitch",
    374: "Sugar - Maroon 5",
    267: "Sugar, We're Goin Down - Fall Out Boy",
    345: "Sunroof - Nicky Youre, dazy",
    396: "Super Bass - Nicki Minaj",
    401: "Super Freaky Girl - Nicki Minaj",
    132: "Super Leap Day (Capital Highway) - Roberto Bazzoni / Nitrome",
    92: "Superman - Goldfinger",
    344: "Superstar - Lupe Fiasco, Matthew Santos",
    130: "Surgeon Simulator (Theme Tune) - Bossa Studios / Black Heron",
    449: "Swang - Rae Sremmurd",
    485: "Sway Back - Nase Foi",
    456: "Sweatbox - Luxxly",
    264: "Sweet but Psycho - Ava Max",
    135: "Sweet Home Alabama - Lynyrd Skynyrd",
    430: "Sweetness - Jimmy Eat World",
    232: "Symphony - Clean Bandit, Zara Larsson",
    476: "Symphony Of Destruction - Megadeth",
    10: "Take Me Out - Franz Ferdinand",
    230: "Talk - Khalid, Disclosure",
    341: "Tears Dry On Their Own - Amy Winehouse",
    285: "Teenage Dirtbag - Wheatus",
    159: "thank u, next - Ariana Grande",
    403: "That Don't Impress Me Much - Shania Twain",
    187: "That's Not My Name - The Ting Tings",
    260: "That's The Way (I Like It) - KC & The Sunshine Band",
    382: "THATS WHAT I WANT - Lil Nas X",
    36: "The Bad Touch - Bloodhound Gang",
    103: "The beginning - ONE OK ROCK",
    37: "The Business - Tiesto",
    372: "The Devil Went Down To Georgia - Korn, Yelawolf",
    400: "The Drill - Magnificence & 7 Skies",
    108: "The Fast Lane - Space Ape Edition - Harry Shotta",
    80: "The Git Up - Blanco Brown",
    220: "The Heinrich Maneuver - Interpol",
    515: "The Impression That I Get - The Mighty Mighty Bosstones",
    235: "The Kids Are Coming - Tones and I",
    52: "The Less I Know the Better - Tame Impala",
    13: "The Middle - Jimmy Eat World",
    129: "The Middle - Zedd, Maren Morris, Grey",
    209: "The Mother We Share - CHVRCHES",
    464: "The Motherload - Mastodon",
    338: "The Seed - AURORA",
    131: "The Smell Of Dirt Is In The Air - Jim Guthrie & J.J. Ipsen",
    134: "The Touch - Stan Bush",
    59: "The Trooper - Iron Maiden",
    82: "The Wire - HAIM",
    309: "Therapy - Electric Enemy",
    461: "Think About Things - Daði Freyr",
    180: "This Could Be Us - Rae Sremmurd",
    333: "This Is How We Do It - Montell Jordan",
    508: "This Is War - Thirty Seconds To Mars",
    278: "Thrash Metal Cassette - Dinosaur Pile-Up",
    301: "Thrift Shop - Macklemore, Ryan Lewis, Wanz",
    302: "Thunderclouds - Labrinth, Sia, Diplo",
    141: "Time Is Running Out - Muse",
    501: "Time of Our Lives - Pitbull, Ne-Yo",
    104: "Time To Waste - Alkaline Trio",
    181: "Together - Brawl Stars, Bad Randoms",
    265: "Tonight, Tonight - Smashing Pumpkins",
    21: "Tornado Of Souls - Megadeth",
    460: "Truth Hurts - Lizzo",
    281: "Tubthumping - Chumbawamba",
    509: "Turbo - The Nah",
    254: "Tusa - KAROL G, Nicki Minaj",
    411: "TWINNEM - Coi Leray",
    250: "Two Princes - Spin Doctors",
    208: "U Can't Touch This - MC Hammer",
    408: "Unholy - Sam Smith, Kim Petras",
    67: "USSEEWA - Ado",
    417: "Vegas - Doja Cat",
    163: "Viva La Vida - Coldplay",
    467: "Wait A Minute! - Willow",
    224: "Wake Me Up - Avicii",
    390: "Waking Up Dreaming - Shania Twain",
    75: "Walk Idiot Walk - The Hives",
    471: "Walking on a Dream - Empire of the Sun",
    200: "We Are Family - Sister Sledge",
    475: "We Different - KULLAH, Jessy Covets",
    277: "We Live Forever - The Prodigy",
    127: "We Won't Cooperate - Brawl Stars, Bad Randoms",
    432: "What A Man Gotta Do - Jonas Brothers",
    394: "What Do You Mean? - Justin Bieber",
    503: "What I Got - Sublime",
    93: "What Would You Do? - City High",
    514: "What You Gonna Do - MADZI",
    490: "What You Know - Two Door Cinema Club",
    280: "What's Golden - Jurassic 5",
    332: "Whenever, Wherever - Shakira",
    154: "Where's your head at - Basement Jaxx",
    435: "Whiskey Glasses - Morgan Wallen",
    272: "White Iverson - Post Malone",
    194: "White Noise - Disclosure, AlunaGeorge",
    94: "Who Let The Dogs Out? - Baha Men",
    323: "Wish - Alien Ant Farm",
    212: "WITHOUT YOU - The Kid LAROI",
    81: "Wolf like me - TV on the radio",
    420: "Wolves - Selena Gomez, Marshmello",
    506: "Word Up - Cameo",
    58: "Wynona's Big Brown Beaver - Primus",
    479: "XO Tour Llif3 - Lil Uzi Vert",
    115: "You Don't Know - 702",
    308: "You Really Got Me - The Kinks",
    51: "you should see me in a crown - Billie Eilish",
    282: "You Spin Me Round (Like a Record) - Murder Mix - Dead Or Alive",
    478: "Young Dumb & Broke - Khalid",
    245: "Youngblood - 5 Seconds of Summer",
    354: "Your Song - Rita Ora",
    429: "Yuh - Illvis Freshly"
}

multi_dict = MultiDict(dictIDtoName)
